[package]
name = "RustRenderMetal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.25.0"
core-graphics-types = "0.1.2"
glam = "0.24.1"
metal = "0.26.0"
winit = "0.28.6"
